"""Email service - sends portfolio reports via email"""
import os
import smtplib
import logging
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def generate_email_content(analysis):
    """Generate HTML email content with portfolio analysis"""
    if not analysis:
        return "Unable to generate portfolio analysis."

    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            .header {{ background-color: #f0f0f0; padding: 20px; border-radius: 10px; }}
            .summary {{ background-color: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0; }}
            .section {{ margin: 20px 0; }}
            .positive {{ color: green; font-weight: bold; }}
            .negative {{ color: red; font-weight: bold; }}
            table {{ border-collapse: collapse; width: 100%; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Portfolio Analysis Report</h1>
            <p>Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>

        <div class="summary">
            <h2>Portfolio Summary</h2>
            <p><strong>Total Portfolio Value:</strong> {analysis['total_value']:,.2f}</p>
            <p><strong>Total P&L:</strong>
                <span class="{'positive' if analysis['total_pnl'] >= 0 else 'negative'}">
                    {analysis['total_pnl']:,.2f} ({analysis['total_pnl_percentage']:+.2f}%)
                </span>
            </p>
            <p><strong>Number of Holdings:</strong> {analysis['holdings_count']}</p>
            <p><strong>Sectors Covered:</strong> {len(analysis['sectors'])}</p>
        </div>

        <div class="section">
            <h2>Top Gainers</h2>
            <table>
                <tr><th>Symbol</th><th>P&L</th><th>P&L %</th><th>Current Value</th></tr>
    """

    for gainer in analysis['top_gainers'][:5]:
        html_content += f"""
                <tr>
                    <td>{gainer['symbol']}</td>
                    <td class="positive">{gainer['pnl']:,.2f}</td>
                    <td class="positive">+{gainer['pnl_percentage']:.2f}%</td>
                    <td>{gainer['current_value']:,.2f}</td>
                </tr>
        """

    html_content += """
            </table>
        </div>

        <div class="section">
            <h2>Top Losers</h2>
            <table>
                <tr><th>Symbol</th><th>P&L</th><th>P&L %</th><th>Current Value</th></tr>
    """

    for loser in analysis['top_losers'][:5]:
        html_content += f"""
                <tr>
                    <td>{loser['symbol']}</td>
                    <td class="negative">{loser['pnl']:,.2f}</td>
                    <td class="negative">{loser['pnl_percentage']:.2f}%</td>
                    <td>{loser['current_value']:,.2f}</td>
                </tr>
        """

    html_content += """
            </table>
        </div>

        <div class="section">
            <h2>Sector Analysis</h2>
            <table>
                <tr><th>Sector</th><th>Value</th><th>P&L</th><th>Holdings</th></tr>
    """

    for sector, data in analysis['sectors'].items():
        pnl_class = 'positive' if data['pnl'] >= 0 else 'negative'
        html_content += f"""
                <tr>
                    <td>{sector}</td>
                    <td>{data['value']:,.2f}</td>
                    <td class="{pnl_class}">{data['pnl']:,.2f}</td>
                    <td>{data['count']}</td>
                </tr>
        """

    html_content += """
            </table>
        </div>

        <div class="section">
            <p><em>This report was generated by Portfolio Reporter.</em></p>
        </div>
    </body>
    </html>
    """

    return html_content


def send_report(analysis, sender_email, email_password, recipient_email):
    """Send portfolio report via email"""
    try:
        html_content = generate_email_content(analysis)

        msg = MIMEMultipart('alternative')
        msg['Subject'] = f'Portfolio Analysis Report - {datetime.now().strftime("%Y-%m-%d")}'
        msg['From'] = sender_email
        msg['To'] = recipient_email

        html_part = MIMEText(html_content, 'html')
        msg.attach(html_part)

        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, email_password)
            server.send_message(msg)

        logger.info(f"Email report sent successfully to {recipient_email}")
        return True

    except Exception as e:
        logger.error(f"Error sending email: {e}")
        return False
